Repository openstax/enki, pull requests merged in 2023-08, with the labels that each got.

#282 Epub nozip
  README.md
  build-concourse/build-corgi.ts
  build-concourse/build-graphs.ts
  build-concourse/env/corgi-local.json
  build-concourse/env/corgi-production.json
  build-concourse/env/corgi-staging.json
  build-concourse/graphs/README.md
  build-concourse/script/generate_preview_urls.sh
  build-concourse/script/override_common_log.sh
  build-concourse/step-definitions.ts
  build-concourse/util.ts
  corgi-concourse-resource/corgi_concourse_resource/in_.py
  corgi-concourse-resource/corgi_concourse_resource/out.py
  corgi-concourse-resource/corgi_concourse_resource/utils.py
  corgi-concourse-resource/tests/data/collection_id
  corgi-concourse-resource/tests/data/content_server
  corgi-concourse-resource/tests/data/repo
  corgi-concourse-resource/tests/data/slugs
  corgi-concourse-resource/tests/test_resource.py
  dockerfiles/docker-entrypoint.sh
  dockerfiles/steps/step-docx-meta.bash
  dockerfiles/steps/step-epub.bash
  dockerfiles/steps/step-pdf-meta.bash
  dockerfiles/steps/step-pdf.bash
  dockerfiles/steps/step-upload-book.bash
  dockerfiles/steps/step-upload-docx.bash
  dockerfiles/steps/step-upload-epub.bash
  dockerfiles/steps/step-upload-pdf.bash
  enki
  step-config.json
  test/test-step-02.bash
  test/test-step-03.bash
  test/test-step-05.bash
  test/test-step-08.bash
  test/test-step-11.bash
Labels: enhancement, CORGI

#291 Update awscli to 1.29.25
  Dockerfile
  bakery-src/scripts/requirements.txt
Labels: kaizen

#296 ignore all anchor tags without href, they are still valid html
  bakery-js/src/epub/page.test.ts
  bakery-js/src/epub/page.tsx
Labels: bug
